Update database guides
civo/docs pull request #76
Opened 2024-01-05 12:34 UTC by s1ntaxe770r

This PR adds:

guides for creating databases using the CLI and Terraform

2024-01-05 12:35 UTC, s1ntaxe770r commented
cc @civo-claire  @kai

2024-01-11 16:15 UTC, kaihoffman requested changes

2024-01-11 16:15 UTC, kaihoffman commented on content/docs/database/getting-started.md
> +You can create a Civo database on the command-line by running the `civo database create` command with a name as the only argument
add full stop at the end of "argument"

2024-01-11 16:15 UTC, kaihoffman commented on content/docs/database/getting-started.md
> +![Database created from Terraform appears on the dashboard](images/mysql-terraform-screen.png)
the DB name in the screenshot doesn't match – would be best to have them matching.

2024-01-12 09:08 UTC, s1ntaxe770r commented on content/docs/database/getting-started.md
> +![Database created from Terraform appears on the dashboard](images/mysql-terraform-screen.png)
hey @kaihoffman  are you referring to the reference name `mysql_db` or the name of the database `mysql-tf`

2024-01-16 15:41 UTC, kaihoffman commented on content/docs/database/getting-started.md
> +![Database created from Terraform appears on the dashboard](images/mysql-terraform-screen.png)
Yeah, I was confused, sorry! This looks OK now.

2024-01-16 15:42 UTC, kaihoffman requested changes

2024-01-16 15:42 UTC, kaihoffman commented on content/docs/database/getting-started.md
> +### Veiwing Database information on Civo CLI
Typo. Should be "Viewing".

2024-01-16 15:42 UTC, civo-claire commented on content/docs/database/images/mysql-terraform-screen.png
Could you replace with an image not in dark mode please? Thanks!

2024-01-22 14:25 UTC, kaihoffman approved these changes

2024-01-22 14:25 UTC, merged